/**
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.validation;

import edu.ucf.cs.whilelang.validation.AbstractWhileLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class WhileLangValidator extends AbstractWhileLangValidator {
}
