/*
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class WhileLangScopeProvider extends AbstractWhileLangScopeProvider {

}
