/*
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractWhileLangValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(edu.ucf.cs.whilelang.whileLang.WhileLangPackage.eINSTANCE);
		return result;
	}
	
}
