/*
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.serializer;

import com.google.inject.Inject;
import edu.ucf.cs.whilelang.services.WhileLangGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class WhileLangSyntacticSequencer extends AbstractSyntacticSequencer {

	protected WhileLangGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_5_0_a;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_5_0_p;
	protected AbstractElementAlias match_Program_CommaKeyword_4_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (WhileLangGrammarAccess) access;
		match_Primary_LeftParenthesisKeyword_5_0_a = new TokenAlias(true, true, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_5_0());
		match_Primary_LeftParenthesisKeyword_5_0_p = new TokenAlias(true, false, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_5_0());
		match_Program_CommaKeyword_4_q = new TokenAlias(false, true, grammarAccess.getProgramAccess().getCommaKeyword_4());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Primary_LeftParenthesisKeyword_5_0_a.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_5_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Primary_LeftParenthesisKeyword_5_0_p.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_5_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Program_CommaKeyword_4_q.equals(syntax))
				emit_Program_CommaKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'not' bexp=Primary
	 *     (rule start) (ambiguity) bval='false'
	 *     (rule start) (ambiguity) bval='true'
	 *     (rule start) (ambiguity) num=INT
	 *     (rule start) (ambiguity) sign=OPPLUS
	 *     (rule start) (ambiguity) vname=ID
	 *     (rule start) (ambiguity) {AExpression.left=}
	 *     (rule start) (ambiguity) {BConj.left=}
	 *     (rule start) (ambiguity) {BDisj.left=}
	 *     (rule start) (ambiguity) {BRelExp.left=}
	 *     (rule start) (ambiguity) {Factor.left=}
	 */
	protected void emit_Primary_LeftParenthesisKeyword_5_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {AExpression.left=}
	 *     (rule start) (ambiguity) {BConj.left=}
	 *     (rule start) (ambiguity) {BDisj.left=}
	 *     (rule start) (ambiguity) {BRelExp.left=}
	 *     (rule start) (ambiguity) {Factor.left=}
	 */
	protected void emit_Primary_LeftParenthesisKeyword_5_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ','?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '(' (ambiguity) ')' 'is' body=Stmt
	 *     name=ID '(' (ambiguity) 'res' rformals=Formals
	 *     vformals=Formals (ambiguity) ')' 'is' body=Stmt
	 *     vformals=Formals (ambiguity) 'res' rformals=Formals
	 */
	protected void emit_Program_CommaKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
