/**
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.whileLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>AExpr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getAExpr()
 * @model
 * @generated
 */
public interface AExpr extends EObject
{
} // AExpr
