/**
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.whileLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assign S</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ucf.cs.whilelang.whileLang.AssignS#getV <em>V</em>}</li>
 *   <li>{@link edu.ucf.cs.whilelang.whileLang.AssignS#getAexp <em>Aexp</em>}</li>
 *   <li>{@link edu.ucf.cs.whilelang.whileLang.AssignS#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getAssignS()
 * @model
 * @generated
 */
public interface AssignS extends S, ElementaryBlock
{
  /**
   * Returns the value of the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>V</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>V</em>' attribute.
   * @see #setV(String)
   * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getAssignS_V()
   * @model
   * @generated
   */
  String getV();

  /**
   * Sets the value of the '{@link edu.ucf.cs.whilelang.whileLang.AssignS#getV <em>V</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V</em>' attribute.
   * @see #getV()
   * @generated
   */
  void setV(String value);

  /**
   * Returns the value of the '<em><b>Aexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Aexp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aexp</em>' containment reference.
   * @see #setAexp(Expr)
   * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getAssignS_Aexp()
   * @model containment="true"
   * @generated
   */
  Expr getAexp();

  /**
   * Sets the value of the '{@link edu.ucf.cs.whilelang.whileLang.AssignS#getAexp <em>Aexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Aexp</em>' containment reference.
   * @see #getAexp()
   * @generated
   */
  void setAexp(Expr value);

  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Label</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(int)
   * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getAssignS_Label()
   * @model
   * @generated
   */
  int getLabel();

  /**
   * Sets the value of the '{@link edu.ucf.cs.whilelang.whileLang.AssignS#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(int value);

} // AssignS
