/**
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.whileLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assign S</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ucf.cs.whilelang.whileLang.AssignS#getVar <em>Var</em>}</li>
 *   <li>{@link edu.ucf.cs.whilelang.whileLang.AssignS#getAexp <em>Aexp</em>}</li>
 * </ul>
 *
 * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getAssignS()
 * @model
 * @generated
 */
public interface AssignS extends S
{
  /**
   * Returns the value of the '<em><b>Var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' attribute.
   * @see #setVar(String)
   * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getAssignS_Var()
   * @model
   * @generated
   */
  String getVar();

  /**
   * Sets the value of the '{@link edu.ucf.cs.whilelang.whileLang.AssignS#getVar <em>Var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' attribute.
   * @see #getVar()
   * @generated
   */
  void setVar(String value);

  /**
   * Returns the value of the '<em><b>Aexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Aexp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aexp</em>' containment reference.
   * @see #setAexp(AExpr)
   * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getAssignS_Aexp()
   * @model containment="true"
   * @generated
   */
  AExpr getAexp();

  /**
   * Sets the value of the '{@link edu.ucf.cs.whilelang.whileLang.AssignS#getAexp <em>Aexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Aexp</em>' containment reference.
   * @see #getAexp()
   * @generated
   */
  void setAexp(AExpr value);

} // AssignS
