/**
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.whileLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>BPrimary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ucf.cs.whilelang.whileLang.BPrimary#getBval <em>Bval</em>}</li>
 * </ul>
 *
 * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getBPrimary()
 * @model
 * @generated
 */
public interface BPrimary extends BExpr
{
  /**
   * Returns the value of the '<em><b>Bval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bval</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bval</em>' attribute.
   * @see #setBval(String)
   * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getBPrimary_Bval()
   * @model
   * @generated
   */
  String getBval();

  /**
   * Sets the value of the '{@link edu.ucf.cs.whilelang.whileLang.BPrimary#getBval <em>Bval</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bval</em>' attribute.
   * @see #getBval()
   * @generated
   */
  void setBval(String value);

} // BPrimary
