/**
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.whileLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Skip S</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getSkipS()
 * @model
 * @generated
 */
public interface SkipS extends S
{
} // SkipS
