/**
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.whileLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>While S</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.ucf.cs.whilelang.whileLang.WhileS#getBexp <em>Bexp</em>}</li>
 *   <li>{@link edu.ucf.cs.whilelang.whileLang.WhileS#getBlock <em>Block</em>}</li>
 * </ul>
 *
 * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getWhileS()
 * @model
 * @generated
 */
public interface WhileS extends S
{
  /**
   * Returns the value of the '<em><b>Bexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bexp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bexp</em>' containment reference.
   * @see #setBexp(BExpr)
   * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getWhileS_Bexp()
   * @model containment="true"
   * @generated
   */
  BExpr getBexp();

  /**
   * Sets the value of the '{@link edu.ucf.cs.whilelang.whileLang.WhileS#getBexp <em>Bexp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bexp</em>' containment reference.
   * @see #getBexp()
   * @generated
   */
  void setBexp(BExpr value);

  /**
   * Returns the value of the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block</em>' containment reference.
   * @see #setBlock(CompoundS)
   * @see edu.ucf.cs.whilelang.whileLang.WhileLangPackage#getWhileS_Block()
   * @model containment="true"
   * @generated
   */
  CompoundS getBlock();

  /**
   * Sets the value of the '{@link edu.ucf.cs.whilelang.whileLang.WhileS#getBlock <em>Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block</em>' containment reference.
   * @see #getBlock()
   * @generated
   */
  void setBlock(CompoundS value);

} // WhileS
