/**
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.whileLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.ucf.cs.whilelang.whileLang.WhileLangFactory
 * @model kind="package"
 * @generated
 */
public interface WhileLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "whileLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ucf.edu/cs/whilelang/WhileLang";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "whileLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WhileLangPackage eINSTANCE = edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl.init();

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.ProgramImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Vformals</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__VFORMALS = 1;

  /**
   * The feature id for the '<em><b>Rformals</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__RFORMALS = 2;

  /**
   * The feature id for the '<em><b>Body</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__BODY = 3;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.FormalsImpl <em>Formals</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.FormalsImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getFormals()
   * @generated
   */
  int FORMALS = 1;

  /**
   * The feature id for the '<em><b>Names</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMALS__NAMES = 0;

  /**
   * The number of structural features of the '<em>Formals</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FORMALS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.SImpl <em>S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.SImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getS()
   * @generated
   */
  int S = 2;

  /**
   * The number of structural features of the '<em>S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int S_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.CompoundSImpl <em>Compound S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.CompoundSImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getCompoundS()
   * @generated
   */
  int COMPOUND_S = 3;

  /**
   * The feature id for the '<em><b>Stmts</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_S__STMTS = S_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Compound S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPOUND_S_FEATURE_COUNT = S_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.AssignSImpl <em>Assign S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.AssignSImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getAssignS()
   * @generated
   */
  int ASSIGN_S = 4;

  /**
   * The feature id for the '<em><b>V</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_S__V = S_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Aexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_S__AEXP = S_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_S__LABEL = S_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Assign S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_S_FEATURE_COUNT = S_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.SkipSImpl <em>Skip S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.SkipSImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getSkipS()
   * @generated
   */
  int SKIP_S = 5;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKIP_S__LABEL = S_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Skip S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SKIP_S_FEATURE_COUNT = S_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.WhileSImpl <em>While S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileSImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getWhileS()
   * @generated
   */
  int WHILE_S = 6;

  /**
   * The feature id for the '<em><b>Bexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_S__BEXP = S_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_S__BLOCK = S_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>While S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHILE_S_FEATURE_COUNT = S_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.IfSImpl <em>If S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.IfSImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getIfS()
   * @generated
   */
  int IF_S = 7;

  /**
   * The feature id for the '<em><b>Bexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_S__BEXP = S_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>S1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_S__S1 = S_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>S2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_S__S2 = S_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>If S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IF_S_FEATURE_COUNT = S_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.AssertSImpl <em>Assert S</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.AssertSImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getAssertS()
   * @generated
   */
  int ASSERT_S = 8;

  /**
   * The feature id for the '<em><b>Bexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_S__BEXP = S_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Assert S</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSERT_S_FEATURE_COUNT = S_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.ElementaryBlockImpl <em>Elementary Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.ElementaryBlockImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getElementaryBlock()
   * @generated
   */
  int ELEMENTARY_BLOCK = 16;

  /**
   * The number of structural features of the '<em>Elementary Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENTARY_BLOCK_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.LabeledExpImpl <em>Labeled Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.LabeledExpImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getLabeledExp()
   * @generated
   */
  int LABELED_EXP = 9;

  /**
   * The feature id for the '<em><b>Be</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABELED_EXP__BE = ELEMENTARY_BLOCK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABELED_EXP__LABEL = ELEMENTARY_BLOCK_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Labeled Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LABELED_EXP_FEATURE_COUNT = ELEMENTARY_BLOCK_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.ExprImpl <em>Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.ExprImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getExpr()
   * @generated
   */
  int EXPR = 10;

  /**
   * The number of structural features of the '<em>Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPR_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.VarRefExprImpl <em>Var Ref Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.VarRefExprImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getVarRefExpr()
   * @generated
   */
  int VAR_REF_EXPR = 11;

  /**
   * The feature id for the '<em><b>Vname</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REF_EXPR__VNAME = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Var Ref Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VAR_REF_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.SignedNumImpl <em>Signed Num</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.SignedNumImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getSignedNum()
   * @generated
   */
  int SIGNED_NUM = 12;

  /**
   * The feature id for the '<em><b>Sign</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNED_NUM__SIGN = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Nval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNED_NUM__NVAL = EXPR_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Signed Num</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIGNED_NUM_FEATURE_COUNT = EXPR_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.NumLitExprImpl <em>Num Lit Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.NumLitExprImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getNumLitExpr()
   * @generated
   */
  int NUM_LIT_EXPR = 13;

  /**
   * The feature id for the '<em><b>Num</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUM_LIT_EXPR__NUM = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Num Lit Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUM_LIT_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.BoolLitExprImpl <em>Bool Lit Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.BoolLitExprImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getBoolLitExpr()
   * @generated
   */
  int BOOL_LIT_EXPR = 14;

  /**
   * The feature id for the '<em><b>Bval</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_LIT_EXPR__BVAL = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Lit Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_LIT_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.NotExprImpl <em>Not Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.NotExprImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getNotExpr()
   * @generated
   */
  int NOT_EXPR = 15;

  /**
   * The feature id for the '<em><b>Bexp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EXPR__BEXP = EXPR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EXPR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.BDisjImpl <em>BDisj</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.BDisjImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getBDisj()
   * @generated
   */
  int BDISJ = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BDISJ__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BDISJ__OP = EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BDISJ__RIGHT = EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>BDisj</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BDISJ_FEATURE_COUNT = EXPR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.BConjImpl <em>BConj</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.BConjImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getBConj()
   * @generated
   */
  int BCONJ = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BCONJ__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BCONJ__OP = EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BCONJ__RIGHT = EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>BConj</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BCONJ_FEATURE_COUNT = EXPR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.BRelExpImpl <em>BRel Exp</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.BRelExpImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getBRelExp()
   * @generated
   */
  int BREL_EXP = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREL_EXP__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREL_EXP__OP = EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREL_EXP__RIGHT = EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>BRel Exp</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BREL_EXP_FEATURE_COUNT = EXPR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.AExpressionImpl <em>AExpression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.AExpressionImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getAExpression()
   * @generated
   */
  int AEXPRESSION = 20;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AEXPRESSION__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AEXPRESSION__OP = EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AEXPRESSION__RIGHT = EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>AExpression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AEXPRESSION_FEATURE_COUNT = EXPR_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link edu.ucf.cs.whilelang.whileLang.impl.FactorImpl <em>Factor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.ucf.cs.whilelang.whileLang.impl.FactorImpl
   * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getFactor()
   * @generated
   */
  int FACTOR = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__LEFT = EXPR_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__OP = EXPR_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR__RIGHT = EXPR_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Factor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACTOR_FEATURE_COUNT = EXPR_FEATURE_COUNT + 3;


  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.Program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Program#getName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Name();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.Program#getVformals <em>Vformals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Vformals</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Program#getVformals()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Vformals();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.Program#getRformals <em>Rformals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rformals</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Program#getRformals()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Rformals();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.Program#getBody <em>Body</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Body</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Program#getBody()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Body();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.Formals <em>Formals</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Formals</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Formals
   * @generated
   */
  EClass getFormals();

  /**
   * Returns the meta object for the attribute list '{@link edu.ucf.cs.whilelang.whileLang.Formals#getNames <em>Names</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Names</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Formals#getNames()
   * @see #getFormals()
   * @generated
   */
  EAttribute getFormals_Names();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.S <em>S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>S</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.S
   * @generated
   */
  EClass getS();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.CompoundS <em>Compound S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Compound S</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.CompoundS
   * @generated
   */
  EClass getCompoundS();

  /**
   * Returns the meta object for the containment reference list '{@link edu.ucf.cs.whilelang.whileLang.CompoundS#getStmts <em>Stmts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stmts</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.CompoundS#getStmts()
   * @see #getCompoundS()
   * @generated
   */
  EReference getCompoundS_Stmts();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.AssignS <em>Assign S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assign S</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AssignS
   * @generated
   */
  EClass getAssignS();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.AssignS#getV <em>V</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>V</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AssignS#getV()
   * @see #getAssignS()
   * @generated
   */
  EAttribute getAssignS_V();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.AssignS#getAexp <em>Aexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Aexp</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AssignS#getAexp()
   * @see #getAssignS()
   * @generated
   */
  EReference getAssignS_Aexp();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.AssignS#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AssignS#getLabel()
   * @see #getAssignS()
   * @generated
   */
  EAttribute getAssignS_Label();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.SkipS <em>Skip S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Skip S</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.SkipS
   * @generated
   */
  EClass getSkipS();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.SkipS#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.SkipS#getLabel()
   * @see #getSkipS()
   * @generated
   */
  EAttribute getSkipS_Label();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.WhileS <em>While S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>While S</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.WhileS
   * @generated
   */
  EClass getWhileS();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.WhileS#getBexp <em>Bexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bexp</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.WhileS#getBexp()
   * @see #getWhileS()
   * @generated
   */
  EReference getWhileS_Bexp();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.WhileS#getBlock <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Block</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.WhileS#getBlock()
   * @see #getWhileS()
   * @generated
   */
  EReference getWhileS_Block();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.IfS <em>If S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>If S</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.IfS
   * @generated
   */
  EClass getIfS();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.IfS#getBexp <em>Bexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bexp</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.IfS#getBexp()
   * @see #getIfS()
   * @generated
   */
  EReference getIfS_Bexp();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.IfS#getS1 <em>S1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>S1</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.IfS#getS1()
   * @see #getIfS()
   * @generated
   */
  EReference getIfS_S1();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.IfS#getS2 <em>S2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>S2</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.IfS#getS2()
   * @see #getIfS()
   * @generated
   */
  EReference getIfS_S2();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.AssertS <em>Assert S</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assert S</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AssertS
   * @generated
   */
  EClass getAssertS();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.AssertS#getBexp <em>Bexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bexp</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AssertS#getBexp()
   * @see #getAssertS()
   * @generated
   */
  EReference getAssertS_Bexp();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.LabeledExp <em>Labeled Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Labeled Exp</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.LabeledExp
   * @generated
   */
  EClass getLabeledExp();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.LabeledExp#getBe <em>Be</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Be</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.LabeledExp#getBe()
   * @see #getLabeledExp()
   * @generated
   */
  EReference getLabeledExp_Be();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.LabeledExp#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.LabeledExp#getLabel()
   * @see #getLabeledExp()
   * @generated
   */
  EAttribute getLabeledExp_Label();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.Expr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expr</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Expr
   * @generated
   */
  EClass getExpr();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.VarRefExpr <em>Var Ref Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Var Ref Expr</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.VarRefExpr
   * @generated
   */
  EClass getVarRefExpr();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.VarRefExpr#getVname <em>Vname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vname</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.VarRefExpr#getVname()
   * @see #getVarRefExpr()
   * @generated
   */
  EAttribute getVarRefExpr_Vname();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.SignedNum <em>Signed Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Signed Num</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.SignedNum
   * @generated
   */
  EClass getSignedNum();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.SignedNum#getSign <em>Sign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Sign</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.SignedNum#getSign()
   * @see #getSignedNum()
   * @generated
   */
  EAttribute getSignedNum_Sign();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.SignedNum#getNval <em>Nval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Nval</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.SignedNum#getNval()
   * @see #getSignedNum()
   * @generated
   */
  EReference getSignedNum_Nval();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.NumLitExpr <em>Num Lit Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Num Lit Expr</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.NumLitExpr
   * @generated
   */
  EClass getNumLitExpr();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.NumLitExpr#getNum <em>Num</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Num</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.NumLitExpr#getNum()
   * @see #getNumLitExpr()
   * @generated
   */
  EAttribute getNumLitExpr_Num();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.BoolLitExpr <em>Bool Lit Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Lit Expr</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BoolLitExpr
   * @generated
   */
  EClass getBoolLitExpr();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.BoolLitExpr#getBval <em>Bval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bval</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BoolLitExpr#getBval()
   * @see #getBoolLitExpr()
   * @generated
   */
  EAttribute getBoolLitExpr_Bval();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.NotExpr <em>Not Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Expr</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.NotExpr
   * @generated
   */
  EClass getNotExpr();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.NotExpr#getBexp <em>Bexp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Bexp</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.NotExpr#getBexp()
   * @see #getNotExpr()
   * @generated
   */
  EReference getNotExpr_Bexp();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.ElementaryBlock <em>Elementary Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Elementary Block</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.ElementaryBlock
   * @generated
   */
  EClass getElementaryBlock();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.BDisj <em>BDisj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BDisj</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BDisj
   * @generated
   */
  EClass getBDisj();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.BDisj#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BDisj#getLeft()
   * @see #getBDisj()
   * @generated
   */
  EReference getBDisj_Left();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.BDisj#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BDisj#getOp()
   * @see #getBDisj()
   * @generated
   */
  EAttribute getBDisj_Op();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.BDisj#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BDisj#getRight()
   * @see #getBDisj()
   * @generated
   */
  EReference getBDisj_Right();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.BConj <em>BConj</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BConj</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BConj
   * @generated
   */
  EClass getBConj();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.BConj#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BConj#getLeft()
   * @see #getBConj()
   * @generated
   */
  EReference getBConj_Left();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.BConj#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BConj#getOp()
   * @see #getBConj()
   * @generated
   */
  EAttribute getBConj_Op();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.BConj#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BConj#getRight()
   * @see #getBConj()
   * @generated
   */
  EReference getBConj_Right();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.BRelExp <em>BRel Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>BRel Exp</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BRelExp
   * @generated
   */
  EClass getBRelExp();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.BRelExp#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BRelExp#getLeft()
   * @see #getBRelExp()
   * @generated
   */
  EReference getBRelExp_Left();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.BRelExp#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BRelExp#getOp()
   * @see #getBRelExp()
   * @generated
   */
  EAttribute getBRelExp_Op();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.BRelExp#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.BRelExp#getRight()
   * @see #getBRelExp()
   * @generated
   */
  EReference getBRelExp_Right();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.AExpression <em>AExpression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>AExpression</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AExpression
   * @generated
   */
  EClass getAExpression();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.AExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AExpression#getLeft()
   * @see #getAExpression()
   * @generated
   */
  EReference getAExpression_Left();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.AExpression#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AExpression#getOp()
   * @see #getAExpression()
   * @generated
   */
  EAttribute getAExpression_Op();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.AExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.AExpression#getRight()
   * @see #getAExpression()
   * @generated
   */
  EReference getAExpression_Right();

  /**
   * Returns the meta object for class '{@link edu.ucf.cs.whilelang.whileLang.Factor <em>Factor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Factor</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Factor
   * @generated
   */
  EClass getFactor();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.Factor#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Factor#getLeft()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Left();

  /**
   * Returns the meta object for the attribute '{@link edu.ucf.cs.whilelang.whileLang.Factor#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Factor#getOp()
   * @see #getFactor()
   * @generated
   */
  EAttribute getFactor_Op();

  /**
   * Returns the meta object for the containment reference '{@link edu.ucf.cs.whilelang.whileLang.Factor#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.ucf.cs.whilelang.whileLang.Factor#getRight()
   * @see #getFactor()
   * @generated
   */
  EReference getFactor_Right();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WhileLangFactory getWhileLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.ProgramImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getProgram_Name();

    /**
     * The meta object literal for the '<em><b>Vformals</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__VFORMALS = eINSTANCE.getProgram_Vformals();

    /**
     * The meta object literal for the '<em><b>Rformals</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__RFORMALS = eINSTANCE.getProgram_Rformals();

    /**
     * The meta object literal for the '<em><b>Body</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__BODY = eINSTANCE.getProgram_Body();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.FormalsImpl <em>Formals</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.FormalsImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getFormals()
     * @generated
     */
    EClass FORMALS = eINSTANCE.getFormals();

    /**
     * The meta object literal for the '<em><b>Names</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FORMALS__NAMES = eINSTANCE.getFormals_Names();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.SImpl <em>S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.SImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getS()
     * @generated
     */
    EClass S = eINSTANCE.getS();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.CompoundSImpl <em>Compound S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.CompoundSImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getCompoundS()
     * @generated
     */
    EClass COMPOUND_S = eINSTANCE.getCompoundS();

    /**
     * The meta object literal for the '<em><b>Stmts</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPOUND_S__STMTS = eINSTANCE.getCompoundS_Stmts();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.AssignSImpl <em>Assign S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.AssignSImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getAssignS()
     * @generated
     */
    EClass ASSIGN_S = eINSTANCE.getAssignS();

    /**
     * The meta object literal for the '<em><b>V</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGN_S__V = eINSTANCE.getAssignS_V();

    /**
     * The meta object literal for the '<em><b>Aexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN_S__AEXP = eINSTANCE.getAssignS_Aexp();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ASSIGN_S__LABEL = eINSTANCE.getAssignS_Label();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.SkipSImpl <em>Skip S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.SkipSImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getSkipS()
     * @generated
     */
    EClass SKIP_S = eINSTANCE.getSkipS();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SKIP_S__LABEL = eINSTANCE.getSkipS_Label();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.WhileSImpl <em>While S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileSImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getWhileS()
     * @generated
     */
    EClass WHILE_S = eINSTANCE.getWhileS();

    /**
     * The meta object literal for the '<em><b>Bexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_S__BEXP = eINSTANCE.getWhileS_Bexp();

    /**
     * The meta object literal for the '<em><b>Block</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHILE_S__BLOCK = eINSTANCE.getWhileS_Block();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.IfSImpl <em>If S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.IfSImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getIfS()
     * @generated
     */
    EClass IF_S = eINSTANCE.getIfS();

    /**
     * The meta object literal for the '<em><b>Bexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_S__BEXP = eINSTANCE.getIfS_Bexp();

    /**
     * The meta object literal for the '<em><b>S1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_S__S1 = eINSTANCE.getIfS_S1();

    /**
     * The meta object literal for the '<em><b>S2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IF_S__S2 = eINSTANCE.getIfS_S2();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.AssertSImpl <em>Assert S</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.AssertSImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getAssertS()
     * @generated
     */
    EClass ASSERT_S = eINSTANCE.getAssertS();

    /**
     * The meta object literal for the '<em><b>Bexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSERT_S__BEXP = eINSTANCE.getAssertS_Bexp();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.LabeledExpImpl <em>Labeled Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.LabeledExpImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getLabeledExp()
     * @generated
     */
    EClass LABELED_EXP = eINSTANCE.getLabeledExp();

    /**
     * The meta object literal for the '<em><b>Be</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LABELED_EXP__BE = eINSTANCE.getLabeledExp_Be();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LABELED_EXP__LABEL = eINSTANCE.getLabeledExp_Label();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.ExprImpl <em>Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.ExprImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getExpr()
     * @generated
     */
    EClass EXPR = eINSTANCE.getExpr();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.VarRefExprImpl <em>Var Ref Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.VarRefExprImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getVarRefExpr()
     * @generated
     */
    EClass VAR_REF_EXPR = eINSTANCE.getVarRefExpr();

    /**
     * The meta object literal for the '<em><b>Vname</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VAR_REF_EXPR__VNAME = eINSTANCE.getVarRefExpr_Vname();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.SignedNumImpl <em>Signed Num</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.SignedNumImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getSignedNum()
     * @generated
     */
    EClass SIGNED_NUM = eINSTANCE.getSignedNum();

    /**
     * The meta object literal for the '<em><b>Sign</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIGNED_NUM__SIGN = eINSTANCE.getSignedNum_Sign();

    /**
     * The meta object literal for the '<em><b>Nval</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIGNED_NUM__NVAL = eINSTANCE.getSignedNum_Nval();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.NumLitExprImpl <em>Num Lit Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.NumLitExprImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getNumLitExpr()
     * @generated
     */
    EClass NUM_LIT_EXPR = eINSTANCE.getNumLitExpr();

    /**
     * The meta object literal for the '<em><b>Num</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUM_LIT_EXPR__NUM = eINSTANCE.getNumLitExpr_Num();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.BoolLitExprImpl <em>Bool Lit Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.BoolLitExprImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getBoolLitExpr()
     * @generated
     */
    EClass BOOL_LIT_EXPR = eINSTANCE.getBoolLitExpr();

    /**
     * The meta object literal for the '<em><b>Bval</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_LIT_EXPR__BVAL = eINSTANCE.getBoolLitExpr_Bval();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.NotExprImpl <em>Not Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.NotExprImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getNotExpr()
     * @generated
     */
    EClass NOT_EXPR = eINSTANCE.getNotExpr();

    /**
     * The meta object literal for the '<em><b>Bexp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_EXPR__BEXP = eINSTANCE.getNotExpr_Bexp();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.ElementaryBlockImpl <em>Elementary Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.ElementaryBlockImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getElementaryBlock()
     * @generated
     */
    EClass ELEMENTARY_BLOCK = eINSTANCE.getElementaryBlock();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.BDisjImpl <em>BDisj</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.BDisjImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getBDisj()
     * @generated
     */
    EClass BDISJ = eINSTANCE.getBDisj();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BDISJ__LEFT = eINSTANCE.getBDisj_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BDISJ__OP = eINSTANCE.getBDisj_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BDISJ__RIGHT = eINSTANCE.getBDisj_Right();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.BConjImpl <em>BConj</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.BConjImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getBConj()
     * @generated
     */
    EClass BCONJ = eINSTANCE.getBConj();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BCONJ__LEFT = eINSTANCE.getBConj_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BCONJ__OP = eINSTANCE.getBConj_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BCONJ__RIGHT = eINSTANCE.getBConj_Right();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.BRelExpImpl <em>BRel Exp</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.BRelExpImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getBRelExp()
     * @generated
     */
    EClass BREL_EXP = eINSTANCE.getBRelExp();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BREL_EXP__LEFT = eINSTANCE.getBRelExp_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BREL_EXP__OP = eINSTANCE.getBRelExp_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BREL_EXP__RIGHT = eINSTANCE.getBRelExp_Right();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.AExpressionImpl <em>AExpression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.AExpressionImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getAExpression()
     * @generated
     */
    EClass AEXPRESSION = eINSTANCE.getAExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AEXPRESSION__LEFT = eINSTANCE.getAExpression_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AEXPRESSION__OP = eINSTANCE.getAExpression_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AEXPRESSION__RIGHT = eINSTANCE.getAExpression_Right();

    /**
     * The meta object literal for the '{@link edu.ucf.cs.whilelang.whileLang.impl.FactorImpl <em>Factor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.ucf.cs.whilelang.whileLang.impl.FactorImpl
     * @see edu.ucf.cs.whilelang.whileLang.impl.WhileLangPackageImpl#getFactor()
     * @generated
     */
    EClass FACTOR = eINSTANCE.getFactor();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__LEFT = eINSTANCE.getFactor_Left();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FACTOR__OP = eINSTANCE.getFactor_Op();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACTOR__RIGHT = eINSTANCE.getFactor_Right();

  }

} //WhileLangPackage
