/*
 * generated by Xtext 2.13.0
 */
package edu.ucf.cs.whilelang.ide


/**
 * Use this class to register ide components.
 */
class WhileLangIdeModule extends AbstractWhileLangIdeModule {
}
